root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -buildvcs=false -o ./tmp/main ./cmd/main.go"
  bin = "./tmp/main"
  exclude_dir = ["tmp", "vendor"]
  include_ext = ["go"]
  pre_cmd = ["make migrate-up"]

[screen]
  clear_on_rebuild = true

[log]
  time = true
