// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Login with email and password, returns access token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Authenticate user",
                "parameters": [
                    {
                        "description": "Login credentials (email and password)",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.LoginResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorUnauthorized"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorValidation"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorInternalServer"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "Invalidate refresh token and clear cookie",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Logout user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.LogoutResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorUnauthorized"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorInternalServer"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Exchange refresh cookie for a new access token",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Refresh access token",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.LoginResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorUnauthorized"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorInternalServer"
                        }
                    }
                }
            }
        },
        "/auth/signup": {
            "post": {
                "description": "Create a new user account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "User signup payload",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorConflict"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorValidation"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorInternalServer"
                        }
                    }
                }
            }
        },
        "/events": {
            "get": {
                "description": "Get all events",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Events"
                ],
                "summary": "List events",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Location",
                        "name": "location",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start Date",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End Date",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.EventListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorInternalServer"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new event (authenticated)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Events"
                ],
                "summary": "Create an event",
                "parameters": [
                    {
                        "description": "Event payload",
                        "name": "event",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateEventRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Event"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorUnauthorized"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorBadRequest"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorInternalServer"
                        }
                    }
                }
            }
        },
        "/events/tickets/register/{id}/status": {
            "put": {
                "description": "update the status of registered ticket",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Events"
                ],
                "summary": "Update registration status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "registration ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Patch payload",
                        "name": "status",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.PatchBookingRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.BookingResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorNotFound"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorInternalServer"
                        }
                    }
                }
            }
        },
        "/events/tickets/{id}/register": {
            "post": {
                "description": "Book a new ticket",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Events"
                ],
                "summary": "Book an event",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Ticket ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.BookingResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorNotFound"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorInternalServer"
                        }
                    }
                }
            }
        },
        "/events/{id}": {
            "get": {
                "description": "Get an event by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Events"
                ],
                "summary": "Get event by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Event ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.EventResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorNotFound"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorInternalServer"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update an existing event (authenticated, owner only)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Events"
                ],
                "summary": "Update an event",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Event ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Patch payload",
                        "name": "event",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.PatchEventRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Event"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorUnauthorized"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorForbidden"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorNotFound"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorBadRequest"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete an event by ID (authenticated, owner only)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Events"
                ],
                "summary": "Delete an event",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Event ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.EventDeleteSuccess"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorUnauthorized"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorForbidden"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorBadRequest"
                        }
                    }
                }
            }
        },
        "/events/{id}/tickets": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new ticket (authenticated)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Events"
                ],
                "summary": "Create a ticket",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Event ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Ticket payload",
                        "name": "ticket",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateTicketRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.TicketResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorNotFound"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorBadRequest"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorInternalServer"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.HealthCheckResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/api.HealthCheckErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.HealthCheckErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "DB_UNAVAILABLE"
                },
                "status": {
                    "type": "string",
                    "example": "unavailable"
                }
            }
        },
        "api.HealthCheckResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "models.Booking": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2026-06-07T15:04:05Z"
                },
                "id": {
                    "type": "string",
                    "example": "e2f1c3a8-7d4b-11ec-90d6-0242ac120003"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.bookingStatus"
                        }
                    ],
                    "example": "pending"
                },
                "ticketId": {
                    "type": "string",
                    "example": "t12345"
                },
                "updated_at": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2026-06-07T15:04:05Z"
                },
                "userId": {
                    "type": "string",
                    "example": "u12345"
                }
            }
        },
        "models.BookingResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/models.Booking"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.CreateEventRequest": {
            "type": "object",
            "required": [
                "dateTime",
                "location",
                "title"
            ],
            "properties": {
                "dateTime": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2026-06-07T15:04:05Z"
                },
                "description": {
                    "type": "string",
                    "example": "Quarterly planning meeting"
                },
                "duration": {
                    "type": "integer",
                    "example": 60
                },
                "location": {
                    "type": "string",
                    "example": "Conference Room A"
                },
                "title": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3,
                    "example": "Board Meeting"
                }
            }
        },
        "models.CreateTicketRequest": {
            "type": "object",
            "required": [
                "price",
                "quantity",
                "type"
            ],
            "properties": {
                "price": {
                    "type": "number",
                    "example": 99.99
                },
                "quantity": {
                    "type": "integer",
                    "example": 2
                },
                "type": {
                    "enum": [
                        "vip",
                        "general"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.TicketType"
                        }
                    ],
                    "example": "vip"
                }
            }
        },
        "models.ErrorBadRequest": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "PAYLOAD_NOT_VALID"
                },
                "message": {
                    "type": "string",
                    "example": "Bad Request"
                }
            }
        },
        "models.ErrorConflict": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "EMAIL_ALREADY_EXISTS"
                },
                "message": {
                    "type": "string",
                    "example": "Conflict"
                }
            }
        },
        "models.ErrorForbidden": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "ACCESS_DENIED"
                },
                "message": {
                    "type": "string",
                    "example": "Forbidden"
                }
            }
        },
        "models.ErrorInternalServer": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "UNKNOWN_ERROR"
                },
                "message": {
                    "type": "string",
                    "example": "Internal Server Error"
                }
            }
        },
        "models.ErrorNotFound": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "EVENT_NOT_FOUND"
                },
                "message": {
                    "type": "string",
                    "example": "Not Found"
                }
            }
        },
        "models.ErrorUnauthorized": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "INVALID_CREDENTIALS"
                },
                "message": {
                    "type": "string",
                    "example": "Unauthorized"
                }
            }
        },
        "models.ErrorValidation": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "VALIDATION_FAILED"
                },
                "fields": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "{\"email\"": " \"invalid email format\"}"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "Validation Failed"
                }
            }
        },
        "models.Event": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2026-06-07T15:04:05Z"
                },
                "dateTime": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2026-06-07T15:04:05Z"
                },
                "description": {
                    "type": "string",
                    "example": "Quarterly planning meeting"
                },
                "duration": {
                    "description": "Duration in minutes",
                    "type": "integer",
                    "example": 60
                },
                "host": {
                    "$ref": "#/definitions/models.Host"
                },
                "id": {
                    "type": "string",
                    "example": "e2f1c3a8-7d4b-11ec-90d6-0242ac120003"
                },
                "location": {
                    "type": "string",
                    "example": "Conference Room A"
                },
                "ticketCount": {
                    "type": "integer"
                },
                "tickets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Ticket"
                    }
                },
                "title": {
                    "type": "string",
                    "example": "Board Meeting"
                },
                "updated_at": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2026-06-07T15:04:05Z"
                },
                "userId": {
                    "type": "string",
                    "example": "u12345"
                },
                "version": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "models.EventDeleteSuccess": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Event deleted successfully"
                }
            }
        },
        "models.EventListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Event"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.EventResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/models.Event"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.Host": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "john@example.com"
                },
                "id": {
                    "type": "string",
                    "example": "u12345"
                },
                "username": {
                    "type": "string",
                    "example": "john"
                }
            }
        },
        "models.LoginResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "user logged in successfully"
                },
                "token": {
                    "type": "string",
                    "example": "eyJhbGci..."
                }
            }
        },
        "models.LogoutResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "user logged out successfully"
                }
            }
        },
        "models.PatchBookingRequest": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "status": {
                    "enum": [
                        "pending",
                        "confirmed",
                        "cancelled"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.bookingStatus"
                        }
                    ],
                    "example": "pending"
                }
            }
        },
        "models.PatchEventRequest": {
            "type": "object",
            "properties": {
                "dateTime": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2026-07-01T09:00:00Z"
                },
                "description": {
                    "type": "string",
                    "example": "Updated description"
                },
                "duration": {
                    "type": "integer",
                    "example": 60
                },
                "location": {
                    "type": "string",
                    "example": "Room B"
                },
                "title": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3,
                    "example": "Board Meeting"
                }
            }
        },
        "models.Ticket": {
            "type": "object",
            "properties": {
                "bookings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Booking"
                    }
                },
                "created_at": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2026-06-07T15:04:05Z"
                },
                "eventId": {
                    "type": "string",
                    "example": "e12345"
                },
                "id": {
                    "type": "string",
                    "example": "e2f1c3a8-7d4b-11ec-90d6-0242ac120003"
                },
                "price": {
                    "type": "number",
                    "example": 99.99
                },
                "quantity": {
                    "type": "integer",
                    "example": 2
                },
                "type": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.TicketType"
                        }
                    ],
                    "example": "VIP"
                },
                "updated_at": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2026-06-07T15:04:05Z"
                },
                "userId": {
                    "type": "string",
                    "example": "u12345"
                }
            }
        },
        "models.TicketResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/models.Ticket"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.TicketType": {
            "type": "string",
            "enum": [
                "vip",
                "general"
            ],
            "x-enum-varnames": [
                "TicketTypeVIP",
                "TicketTypeGeneral"
            ]
        },
        "models.User": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "id": {
                    "type": "string",
                    "example": "u12345"
                },
                "password": {
                    "type": "string",
                    "minLength": 8,
                    "example": "P@ssw0rd!"
                },
                "username": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 3,
                    "example": "johndoe"
                }
            }
        },
        "models.bookingStatus": {
            "type": "string",
            "enum": [
                "pending",
                "confirmed",
                "cancelled"
            ],
            "x-enum-varnames": [
                "BookingStatusPending",
                "BookingStatusConfirmed",
                "BookingStatusCancelled"
            ]
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Booking Event API",
	Description:      "API for booking events",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
